### ISSUE TITLE
Games plugin - eightball, roulette, dice, FML, etc.

### ISSUE THREAD

**Issue by GLolol** [GLolol/PyLink#122]
The goal of this is to demonstrate PyLink as not only a relay daemon, but a somewhat versatile IRC services framework too.

- [x] dice
- [x] eightball
- [x] fml
- [ ] roulette

----

- message filters? (probably not, the core doesn't support overriding messages like that)

**Comment by DanielOaks** [comment]
I'm playing with this over in my branch [devel+games](https://github.com/DanielOaks/PyLink/tree/devel%2Bgames), will update when I have some news.

**Comment by GLolol** [comment]
Some more work will have to go into a "roulette" function. afaik some implementations are completely random, while others actually check for how many shots have passed, etc.

Will close this for now.
