### ISSUE TITLE
[discuss] Overhaul permissions

### ISSUE THREAD

**Issue by GLolol** [GLolol/PyLink#190]
Work is being tracked in the wip/perms branch.

- [X] Permissions support should be integrated in core, with the introduction of `permissions.checkPermissions()` replacing `irc.checkAuthenticated()` for plugins that want to use the new permissions API. 
- [X] Plugins will be able to do things like `permissions.checkPermissions('automode.manage.#channel')`, which raises NotAuthorizedError if the check fails. 
- [x] Permissions are defined in the config file, as a mapping of targets or hostmasks to a list of permissions for each. The format would look something like this:

```
permissions:
    "$ircop":
        - x.y.z
        - admin.control
```

- [x] Plugins should be able to register a set of default permissions (e.g. via a command like `permissions.addDefaultPermissions({'$ircop': ['relay.linkchannels', 'relay.delinkchannels']})`. If the permissions key in the config is missing, the fallback will be the combination of default perms defined by every loaded plugin.

- [x] Permissions should eventually support wildcards, so that having a permission like `modebot.manage.*` should provide `modebot.manage.#channel`, etc.

- [x] Permissions should be updated on REHASH.

### Redoing login and auth
See #319.

**Comment by siniStar7boy** [comment]
:+1:

**Comment by DanielOaks** [comment]
Something along these lines makes sense, esp. when you start getting into more user-facing modules such as the games stuff. Particularly for things like checking channel privileges of users, being able to do it through services directly rather than just isOpPlus (prevents people from being able to do bad things when netsplits and such happen).

Will probably take some work to write it up nicely though, first thing that pops into my head is being able to automagically map services accounts to PyLink accounts. Need to come up with some use cases for something like that to find out how to best design the linking process (and how we can nicely interact with the different services software out there).

**Comment by GLolol** [comment]
Account systems are basically useless without permissions though. The simple `isOper`, `isOpPlus`, `checkAuthenticated`, etc. checks should probably check if there is a loaded permissions system, and pass all calls to that if so. The basic login / auth system using oper privileges and the admin password which we have right now can probably stay where it is.

For a design of services integration, simply tracking the services account name (for atheme and modern anope) should be okay for most cases. Biggest catches are people renaming their account or having it dropped, because then permissions could possibly be hijacked.

Regarding a permissions system, I haven't decided who exactly should be allowed to manipulate privileges. Each permission name could possibly look like `<modulename>.`<commandname>` (e.g. `opercmds.kill`), which can then be added to permission lists for accounts, hostnames, or ext targets in the future (#170). Global permissions should take precedence over any channel permissions. Should a command be allowed globally, channel ops should still be allowed to turn it off in their channel, for example.

**Comment by DanielOaks** [comment]
Definitely, that's what I'm thinking with the isOper/isOpPlus/etc calls.

Mhmm, I wonder whether they have any unique identifier along with just the account name (random account uuid/email/etc passed along with the first time we see it).

**Comment by GLolol** [comment]
Atheme uses account UIDs (entity IDs) internally, but it doesn't propagate them to other servers.

**Comment by GLolol** [comment]
Changed my mind about the services account mapping. We can just assign permissions to services accounts when #170 gets done.
