### ISSUE TITLE
Hybrid Protocol Module

### ISSUE THREAD

**Issue by DanielOaks** [GLolol/PyLink#198]
This is an issue to track the implementation of the Hybrid proto module in the [wip/hybrid](https://github.com/GLolol/PyLink/tree/wip/hybrid) branch.

Bursts could probably be handled more 'properly', but that would require restructuring PyLink proper some more.

Outgoing commands:
* [x] mode ~~(check 10-cmode-param limit todo)~~
* [x] sjoin
* [x] spawnServer
* [x] squit
* [x] topicBurst - aeb6547
* [x] updateClient (~~confirm this works 100% fine~~) - 0be8344. Only CHGHOST is supported via Hybrid SVSMODE.

Misc:
* [x] Services account tracking
* [x] Incoming SVSMODE / vHost tracking

--

Note from @GLolol: As of GLolol@f35008a, mode, sjoin, spawnServer, and squit inherit from protocols/ts6 and seem to work!  The last two do not.

**Comment by GLolol** [comment]
Another note: for outgoing host changes (via SVSMODE) to work, it appears that PyLink must be U-Lined.

**Comment by DanielOaks** [comment]
I think this can be closed since it's merged into devel (or do we only close once it's in master?)

**Comment by GLolol** [comment]
I usually close when merging into devel.
