### ISSUE TITLE
[proposal] Split up utils module into more relevant sections

### ISSUE THREAD

**Issue by GLolol** [GLolol/PyLink#199]
`utils` is sort of a mess right now; it has literally all the core functions that don't belong elsewhere. Perhaps splitting it into the following categories would make it more intuitive for future module coders, though this may cause a plugin API break:

- [ ] `utils.irc`: IRC-related functions that are not dependent on a specific IRC object (e.g. `isServerName`).
    - All `utils` functions that require an IRC object (`getHostmask`, `checkAuthenticated`, all the mode handling stuff, etc.) should more or less be moved into `Irc()` itself.
    - Likewise, the UID generator classes should be moved into the respective protocol modules.
- [ ] `utils.core`: `add_hook`, ~~`add_cmd`~~ `commandHandler`, `loadModuleFromFolder`, possibly everything else?
- [x] `utils.structures` or a `structures` module: things like KeyedDefaultdict should go here. Possibly DataStore too?

----
edits 23/04/2016: `commandHandler` (#197) probably belongs in either `classes` or `utils.core`. Mention DataStore also.
edits 24/04/2016: Data structures aren't conventionally "utilities", so maybe they're better off oging outside.

**Comment by DanielOaks** [comment]
Yeah I can see `add_hook` moving to `utils.core`, can't see another place for it at the moment.

I think the `cmd` stuff should be inherently linked to CommandHandlers as I'm writing up in the wip/games branch (and from there, inherently linked to BotClients) eventually, but I'd be fine with it moving there for now. I'll end up making the core/plugin changes to all that as I get further with my work, will end up splitting it around core more properly and integrating it nicely with the rest of the system.

I have some utils stuff from my library [here](https://github.com/DanielOaks/girc/blob/master/girc/utils.py), feel free to take a look and steal any useful functions from there (copyright info is commented just above them, where required).

**Comment by GLolol** [comment]
You're right about `add_cmd`! (slipped my mind)

Eventually, the core should be transitioned over to CommandHandlers (#112).

CaseInsensitiveDict looks quite useful for the future. A case insensitive defaultdict would also be awesome, now that I think about it.

**Comment by DanielOaks** [comment]
Yeah. Something I've used a few times is a case-insensitive dict that respects IRC casemapping, same for case-insensitive lists (to hold things like nicknames, channel names, etc).

The file with the classes in it is [here](https://github.com/DanielOaks/girc/blob/master/girc/imapping.py), with the helper functions to auto-create them with the right casemapping (that go on something like `Irc`, or the class that actually knows what the casemapping is) [here](https://github.com/DanielOaks/girc/blob/master/girc/client.py#L164).

Feel free to steal any of that if useful.

**Comment by GLolol** [comment]
I've done the bulk of moving IRC-object-bound functions into Irc(). The status quo works for everything else for now. `add_cmd` will get deprecated when command handlers are finished, but I don't think any sorting otherwise is needed.
