### ISSUE TITLE
Consider usage of InspIRCd's m_servprotect

### ISSUE THREAD

**Issue by Techman-** [GLolol/PyLink#243]
Although PyLink technically may not need it, if PyLink is given a U-Line it can then choose to introduce clients with just `+k`, which marks the psuedobot as a network service and also prevents it from being booted from channels (which may be unintended) by users and opers alike.

And in the grand scheme of things, a U-Lined PyLink can do anything. You won't need +o to do special commands anyways.

**Comment by GLolol** [comment]
This feature has been added in the **devel** (testing) branch, using a `protect_services` config option in the `bot:` section. A U-Line for PyLink is needed for this to work properly.

Thanks for the suggestion!
