### ISSUE TITLE
RPL_WHOISCHANNELS (319) always needs sentinel 

### ISSUE THREAD

**Issue by cooper** [GLolol/PyLink#286]
This affects WHOIS queries handled by PyLink for users which are only in one relayed channel. Numeric 319 RPL_WHOISCHANNELS is sent without a prefixing colon on the last argument. While this is technically valid, (He)xchat and friends don't like it.

```
>> :mad.is.annoying 319 mad Guest12316|ovd #o
```
Shows as
```
* [Guest12316|ovd] o
```

**Comment by GLolol** [comment]
Should the last argument include all the channels? i.e. `:mad.is.annoying 319 mad Guest12316|ovd :#o` or `:mad.is.annoying 319 mad Guest12316|ovd :#test #o`

**Comment by cooper** [comment]
Yes, all the channels should be in a single colon-prefixed final parameter.

**Comment by GLolol** [comment]
I can't reproduce this. https://github.com/GLolol/PyLink/blob/master/coremods/handlers.py#L61-L62

Are you sure you're not doing a local WHOIS instead?

**Comment by cooper** [comment]
```
GET(mad.is.annoying): :902 319 000AAAABL Guest12316|ovd :#o
```
Looks ok. Must be a juno bug.
