### ISSUE TITLE
Clientbot: IRCv3 support

### ISSUE THREAD

**Issue by GLolol** [GLolol/PyLink#290]
#### Base Extensions
- [x] *Properly* implemented [capability negotiation](http://ircv3.net/specs/core/capability-negotiation-3.1.html)
- [x] [`multi-prefix`](http://ircv3.net/specs/extensions/multi-prefix-3.1.html)
- [x] [`sasl`](http://ircv3.net/specs/extensions/sasl-3.1.html)
#### Optional Extensions

Note: a subset of the available extensions are to be implemented because not all of them are incredibly useful for Clientbot.
- [x] [`account-notify`](http://ircv3.net/specs/extensions/account-notify-3.1.html)
    - This needs WHOX support to also enumerate users on JOIN, but that's a feature for some other time...
- [x] [`away-notify`](http://ircv3.net/specs/extensions/away-notify-3.1.html)
- [x] [`extended-join`](http://ircv3.net/specs/extensions/extended-join-3.1.html)
#### Base Extensions
- [x] [Basic capability negotiation / `cap-notify`](http://ircv3.net/specs/core/capability-negotiation-3.2.html)
- [x] [Message tags](http://ircv3.net/specs/core/message-tags-3.2.html)
- [x] ~~[`metadata`](http://ircv3.net/specs/core/metadata-3.2.html)~~ deprecated upstream
- [ ] [`monitor`](http://ircv3.net/specs/core/monitor-3.2.html)
#### Optional Extensions
- [x] [`account-tag`](http://ircv3.net/specs/extensions/account-tag-3.2.html)
- [x] [`chghost`](http://ircv3.net/specs/extensions/chghost-3.2.html)
- [x] [`sasl`](http://ircv3.net/specs/extensions/sasl-3.2.html)
- [x] [`userhost-in-names`](http://ircv3.net/specs/extensions/userhost-in-names-3.2.html)

**Comment by cooper** [comment]
PROTOCTL*

**Comment by GLolol** [comment]
@cooper Fixed, thanks

**Comment by GLolol** [comment]
The bulk of the extensions relevant to us have been implemented, though I'll leave out monitor for now because nothing is actively using it.
