### ISSUE TITLE
Relay should reject LINK requests if the local channel has lower TS than the remote

### ISSUE THREAD

**Issue by GLolol** [GLolol/PyLink#301]
This will probably reduce instances of:
- Channels getting modes cleared when they shouldn't be.
- Ops being confused to why they were suddenly deopped.
- Me yelling at other linked admins for reusing channel names in the first place...

**Comment by cooper** [comment]
You could check if the calling user is the only person in the channel, and if so, recommend that they cycle. If there are others, have PyLink recommend that they use a different channel name and show the syntax for doing so.
