### ISSUE TITLE
Fix help text with blank lines

### ISSUE THREAD

**Issue by cooper** [GLolol/PyLink#306]
The long form HELP command splits the help text by newline and sends one reply per line. Blank lines are sent like `:<UID> NOTICE <UID> :` with no text in the text parameter. This is invalid in the client protocol and is ignored by most IRCds even in server protocols.

It is customary to send either a single space or tab character when a visually blank line is desired.

Easy fix: just add something around [here](https://github.com/GLolol/PyLink/blob/e56c9640dcf11aa7a49bedf328a375383fe3b1bd/utils.py#L292) that rewrites `''` as `' '` or `"\t"`.

**Comment by GLolol** [comment]
Alternatively, we could just ignore empty lines in reply().
