### ISSUE TITLE
Introduce NotEnoughArgumentsError abstraction

### ISSUE THREAD

**Issue by GLolol** [GLolol/PyLink#324]
Something like

``` python
raise NotEnoughArgumentsError(1, 'target', 'payload')
```

should neatly be translated into `Error: Not enough arguments. Needs 1-2: target, payload (optional).` The first integer argument specifies how many arguments are _required_, and the rest are suffixed with "(optional)".

**Comment by IotaSpencer** [comment]
<script src="https://gist.github.com/IotaSpencer/fb8c18e3e967937f01ff8f69c3d58684.js"></script>

**Comment by IotaSpencer** [comment]
Got a small prototype working [here](https://gist.github.com/IotaSpencer/fb8c18e3e967937f01ff8f69c3d58684)

**Comment by GLolol** [comment]
Closing in favor of argparse integration (#6). The latter is a better solution for new plugins since it already formats usage errors when given the wrong set of arguments.
