### ISSUE TITLE
No Support for u2.10.12.10+snircd(1.3.4a)

### ISSUE THREAD

**Issue by Manuelchen** [GLolol/PyLink#329]
Hello, I wanted to use PyLink .
However, I get a problem appears.

2016-09-05 00:33:53,755 [INFO] Connecting to network 'snircd' on ***.***.***.***:4400
2016-09-05 00:33:53,763 [INFO] snircd Starting ping schedulers....
2016-09-05 00:33:53,764 [INFO] snircd Server ready; listening for data.
2016-09-05 00:33:53,779 [ERROR] snircd No data received, disconnecting!
2016-09-05 00:33:53,780 [INFO] snircd Going to auto-reconnect in 5 seconds.

Connect {
	name ="pylink.freeirc.de";
	host = "***.***.***.***";
	vhost = "freeirc.de";
	password = "*********";
	class = "90";
	port = 4400;
	hub = "*.*";
	autoconnect = no;
};

*** Notice -- Received unauthorized connection from pylink.freeirc.de. from irc server

**Comment by GLolol** [comment]
Only [nefarious2](https://github.com/evilnet/nefarious2) (a \_modern\_ P10 varient) is officially supported. 
Your issue looks like a configuration error though: did you add an extra `.` to the PyLink hostname for example? It's showing as `pylink.freeirc.de.` instead of `pylink.freeirc.de`

**Comment by Manuelchen** [comment]
Connect {
	name ="pylink.freeirc.de";
	host = "176.9.233.9";
	vhost = "freeirc.de";
	password = "x41CY4v5N02Hr2Xc41";
	class = "90";
	port = 4400;
	hub = "*.*";
	autoconnect = no;
};

The configurations are certainly correct.

**Comment by GLolol** [comment]
I meant in your PyLink configuration, not the IRCd.

**Comment by Manuelchen** [comment]
snircd:
        ip: 212.227.91.179
        port: 4400
        recvpass: "x41CY4v5N02Hr2Xc41"
        sendpass: "x41CY4v5N02Hr2Xc41"
        hostname: "pylink.freeirc.de"

        # For P10, the SID and SID range options are just numbers. Make sure nothing
        # else is using the range you're reserving for PyLink.
        sid: 50
        sidrange: "100-150"
        channels: ["#lounge"]
        protocol: nefarious
        autoconnect: 5
        netname: "FreeIrc"

**Comment by GLolol** [comment]
Did you rehash your IRCd after adding the link block? Also, verify that 176.9.xyz.abc is the correct IP; i.e. PyLink is using it to connect outwards.

**Comment by Manuelchen** [comment]
I have a one ./rehash run the ip checked . I have everything already done , it does not work .

**Comment by GLolol** [comment]
From [README](https://github.com/GLolol/PyLink#extended-support):
> Other TS6 and P10 variations may work, but are not officially supported.

For what it's worth, I haven't verified whether the nefarious protocol module can actually link to other P10/IRCu variants. Anything other than nefarious2 isn't officially supported - snircd may be considered in the future if there's reasonable demand, and enough time for me or someone else to implement it.

**Comment by Manuelchen** [comment]
It would Great, if snircd supports will would

**Comment by GLolol** [comment]
See #330.

**Comment by GLolol** [comment]
@Manuelchen base support for snircd and other p10 variants has been implemented in the **devel** branch, feel free to test it out and open a new issue if things still don't work. FWIW I was able to connect to snircd using the old nefarious protocol module, and aside from a bunch of unknown MODE warnings, it seemed to work fine.
