### ISSUE TITLE
PyLink: Check if Channels are abandoned and DESTROY

### ISSUE THREAD

**Issue by siniStar7boy** [GLolol/PyLink#346]
I am not sure if the functionality already exists, but realized this may be helpful for PyLink in reducing _abandoned channels_ on networks and such.  

**Proposal:** PyLink checks the original network channel that the channel was `CREATE`d on and if there are no users for 7 or more days, it `DESTROY`'s the channel and removes any Automode entries for the channel.    

If this functionality already exists, please feel free to close. :)

**Comment by GLolol** [comment]
I'll say no to this:

1) Relay and Automode are two separate entities: destroying a channel via relay shouldn't clear access entires or vice versa
2) Tracking a channel's "usage" adds a lot of extra processing to an already massive relay plugin and is really beyond its scope: it's up to network administration to purge dead channels.

**Comment by GLolol** [comment]
Also... 7 days is way too low of a limit., and having to get everyone relink a channel after it "expires" will only be a major pain

**Comment by siniStar7boy** [comment]
It was a _suggestion_.  Network staff _rarely_ remove abandoned channels from what I have seen in the past, _nor do the users creating them when they leave or lose interest._  In any event, as mentioned - just a suggestion.  Maybe will be more necessary as admins have to prune through longer lists of abandoned channels in the future. :)
