### ISSUE TITLE
Add a logout command

### ISSUE THREAD

**Issue by GLolol** [GLolol/PyLink#370]

**Comment by koaxirc** [comment]
Can you also add a FLOGOUT command for the Administrator to force other users out?

**Comment by GLolol** [comment]
@koaxirc To clarify, this command is just for logging out of PyLink, not network services

**Comment by koaxirc** [comment]
@GLolol Yes, I know, suggesting it incase you don't want someone to have access; this way the Pylink Administrator (main one, or anyone with equal permissions can log out another member) so they would have to attempt login again (incase you delete their user or change something)

**Comment by GLolol** [comment]
Ah, that should be simple enough to add. I think just adding an optional argument to `logout` would suffice: 
- `logout` with no args = logging out yourself
- `logout <nick>` attempts to force a logout on that person.

**Comment by IotaSpencer** [comment]
this would work wonders if someone got ahold of credentials but didn't know how to use them
