### ISSUE TITLE
Occasionally users go missing on "link"

### ISSUE THREAD

**Issue by koaxirc** [GLolol/PyLink#375]
This happens ONLY when prefix is disabled

You'll ocasonally see an output:
[19:56:31] <PyLink> [from WWE-News/axon] [Searching For: Peaky Blinders]
[19:56:31] <PyLink> [from WWE-News/axon] Sorry - Cannot find Peaky Blinders

Wouldnt it be possible to attempt syncing at the end of a link? And by that I mean, once PyLink finishes it's inital loading of the networks, it does 1 final check at the end to detect missing clients? 

The only other solution I see for this is to add mandatory sequencing

Example

inspircd:
        ip: 127.0.0.1
        port: 1234
        recvpass: "password"
        sendpass: "password"
        netname: "Inspircd"
        hostname: "the.first.network"
        sid: "0AL"
        sidrange: "8##"
        channels: ["#bugsbunny"]
        protocol: "inspircd"
        autoconnect: 100
        pingfreq: 180
        separator: "/"
        sequence: 1

next_server:
        ip: 123.222.111.123
        port: 1234
        recvpass: "password"
        sendpass: "password"
        netname: "Inspircd"
        hostname: "the.second.network"
        sid: "1AL"
        sidrange: "8##"
        channels: ["#bugsbunny"]
        protocol: "inspircd"
        autoconnect: 100
        pingfreq: 180
        separator: "/"
        sequence: 2 ..And so on and so forth
and it wont begin the (INITAL-FIRST LOAD) of a network until the previous network is loaded
I have a feeling it's being caused by everything loading at once

**Comment by GLolol** [comment]
What version of PyLink are you using?

**Comment by koaxirc** [comment]
[22:45:48] <~PyLink> PyLink version 1.0.3 (in VCS: 1.0.3-3-ge4b2ea6), released under the Mozilla Public License version 2.0.
[22:45:49] <~PyLink> The source of this program is available at https://github.com/GLolol/PyLink.

**Comment by GLolol** [comment]
I have a feeling this may be related to disabling tag_nicks in relay - ie there might be some nick collision that isn't being caught properly.

Can you enable a debug log and see if there's anything related to KILL or SAVE (the latter forces nicks to UIDs on nick collision)? Use `egrep 'KILL|SAVE ' log/*debug*.log` in the PyLink conf folder, for example.

**Comment by GLolol** [comment]
These two lines seem of interest:

```
pylink-errors.log.4:2016-12-18 01:03:29,844 [DEBUG] (axon) -> :803 UID WWE-News 0 1482041009 WWE-News mask-p23t6g.axon.pw 803AAAAA0 0 +xt mask-p23t6g.axon.pw * * :WWE-News
pylink-errors.log.4:2016-12-18 01:03:33,172 [DEBUG] (axon) <- :001 UID WWE-News 0 1481560439 WWE-News znc.axon.pw 0010JYJ7Z WWE-News +iowrxzH Axon-82AE19BD.axon.pw Axon-82AE19BD.axon.pw PtJzvA== :WWE-News
```

When PyLink receives a user introduction after it spawns a client of the same name, no validation is done to make sure the new name is respected. So, the solution seems to be to handle nick collisions ourselves (#285).

**Comment by koaxirc** [comment]
After switching to that branch, and updating, restarting, it appears all users from all sides are present. I see no missing users anymore.

**Comment by GLolol** [comment]
Awesome!
