### ISSUE TITLE
Missing user X in SJOIN

### ISSUE THREAD

**Issue by Ryan-Goldstein** [GLolol/PyLink#378]
When a PyLink connection is reestablished, for particularly large channels, I see in the status window messages like:

Missing user 80 in SJOIN for #wicked from mjf.relay (:803 SJOIN 1462329313 #wicked :+803AAAAAZ +803AAAAA0 +803AAAAA1 +803AAAAA2 +803AAAAAP +803AAAAAI ~@+803AAAAAE +803AAAAAC +803AAAAAF +803AAAAA3 803AAAAAT +803AAAAA4 +803AAAAA5 +803AAAAA6 +803AAAAAS +803AAAAA8 *@803AAAAA7 ~@+803AAAAA9 +803AAAABA +803AAAAAR +803AAAABB +803AAAABC @+803AAAAAG +803AAAABD ~@803AAAAAH +803AAAABE +803AAAAAW +803AAAAAA *@803AAAABF +803AAAAAB +803AAAAAY +803AAAABG +803AAAABH +803AAAAAJ +803AAAABI ~@80

It appears that PyLink isn't respecting a character limit somewhere, which may be resulting in missing/invisible users or something.

**Comment by GLolol** [comment]
Should be fixed by f851dc8.
