### ISSUE TITLE
Make servprotect configurable

### ISSUE THREAD

**Issue by GLolol** [GLolol/PyLink#395]

**Comment by IotaSpencer** [comment]
isn't this already done? or am i missing something

**Comment by GLolol** [comment]
Read the code: https://github.com/GLolol/PyLink/blob/master/plugins/servprotect.py#L7-9

**Comment by IotaSpencer** [comment]
Oh I see

**Comment by IotaSpencer** [comment]
Would you like a servprotect section of the config, or place some keys for length and time below them in a certain format
