### ISSUE TITLE
More beneficial to use 'isinstance'?

### ISSUE THREAD

**Issue by IotaSpencer** [GLolol/PyLink#410]
Per https://github.com/GLolol/PyLink/blob/devel/utils.py#L247

```python
        # Ensure type safety: pluralize strings if only one channel was given, then convert to set.
        if type(channels) == str:
            channels = [channels]
        channels = set(channels)
```

type() will throw an exception if the type is not correct, isinstance() returns false itself.

**Comment by jameswritescode** [comment]
It's also recommended in general to use `isinstance` over `type`.

**Comment by GLolol** [comment]
Patches welcome \o/
