### ISSUE TITLE
FORCE TS Update for channels

### ISSUE THREAD

**Issue by koaxirc** [GLolol/PyLink#415]
Is it possible to add an option for a pylink administrator to forceTS synchronization? 

so if SERVER A has #channel and server B has #same-channel If one of the servers allows the other server to "have" the channel on the pylink a command could be issued to force the server with the LONGEST channel uptime, to tell the OTHER server to TS update so the channels can be linked

(Unless the TS value is set to some unheard of time, like I don't know, 1970)

Because it's not a fun task clearing the channel, especially if once the channel is claimed by a network, any other remote network cant use its settings (unless a shared claim) is there.

I'd restrict it to the pylink administrator so that it cannot be abused.

I suggest this because when you start having 10 pylink servers (for example) clearing channels on 10 networks if some error occures isnt a fun thing to have to do.

**Comment by GLolol** [comment]
I'm not really understanding what this says, but when you link channels together the one with the lowest TS will always win (unless there's some bug I'm not aware of). Unfortunately there's no way to force a channel's TS to be newer than what it already is, as IRCds simply don't allow this. Any TS issues should be fixed in 1.1 already, so 1970 dates can (hopefully?) really be a thing of the past.

**Comment by koaxirc** [comment]
Lets say I have #main on my irc server
and server2 has #main but my channel was created before theres, and i have 50 people,
their channel was created 2 weeks after, and they have 250 people.

Well, as opposed to ME being forced to remove the users (because we both want to use #main as the channel) a command to msg pylink forceTS #main <server1> <server2> and if my SERVER has the bigger uptime, it will join force their channel TS value to go to the oldest one, (mine) so that the channels can link together successfully

**Comment by koaxirc** [comment]
The way I do it now is a pain, I have to create the pylink on the server that has the OLDEST uptime, then link all the channels to it, so they all update their TS value, then I have to DROP the channel in the pylink, create it on the PROPER server, and relink, because the TS value has been updated already.

**Comment by GLolol** [comment]
I think this would be better served with an option in the `link` command to override the TS check. For obvious reasons, that should require a separate permission.
