### ISSUE TITLE
Opt-in G/KLINE relaying, similar to the no_ips options

### ISSUE THREAD

**Issue by GLolol** [GLolol/PyLink#521]
This would preferably be added after UNGLINE support, see #139

**Comment by xnite** [comment]
Nice, I like it :+1:

**Comment by GLolol** [comment]
We discussed this further on IRC and decided that implicit KLINE relaying may not be the best solution. There are several issues to such an implementation:

- The "weakest link", whether this be a malicious/compromised/mistaken oper or a misconfigured session limit, can easily wreak havoc by banning something it shouldn't.
- KLINE relaying goes against the concept of partial network links and creates animosity when opers disagree on policy. If KLINEs are shared, opers are essentially shared as well; this is not what relay intends to support.

(On a side note, there is no reason for this feature to be part of relay proper - ban syncing can be a completely independent plugin since it has nothing to do with the channel sharing relay provides)
