### ISSUE TITLE
what is commands kick from Pylink?

### ISSUE THREAD

**Issue by darksis** [GLolol/PyLink#77]
Hola GLolol i try very much to understand how i kick someone from channel and i try to write it in pm
kick bla #mIRCx RoBot bla bla
and i get error
<pylink> Uncaught exception in command 'kick': LookupError: No such PyLink PseudoClient exists.
if do you can please explain to me what i need to do for it?

**Comment by GLolol** [comment]
The first field "bla" must be the name of a PyLink client. In this case, "PyLink" or whatever you configured in `config.yml`.
