### ISSUE TITLE
Rewrite logging system

### ISSUE THREAD

**Issue by GLolol** [GLolol/PyLink#83]
The current logging system is very simple and doesn't allow for a lot of flexibility. A new log system would be a lot more configurable, with a `log:` block in config that supports multiple targets, each with their own level.

#### Things to implement:
- [x] Logging targets: only one `stdout` type block can be set, but there can be multiple channels and files to log to if desired.
    - ~~Probably no support for multiple file targets - unlike other services packages with special log levels e.g Atheme's `request; register; denycmd, ...`), we only have the simple tiered one from the logging module.~~ Multiple file targets done in 08fd50d
    
    - We can send different log levels to different files, which is done in 08fd50d :)

- [x] ~~Add an `irc.log` function that logs with the network name (and possibly the calling plugin) automatically prepended.~~
    - ~~In the future, plugins should use these functions instead of importing the `log` library, as that would only send text to files or disk.~~
    - e.g. `irc.log.debug('text')` would be equal to `log.debug('(%s) text', irc.name)`

    - **This probably isn't worth doing as it adds *more* complexity to the core instead of making things much simpler.**
- [x] Adding channels as logging targets. 14efb27 0d4655c

#### Possibly for later
- Ability to rotate log files (they get huge when DEBUG is turned on).
- Configurable log format.
- Log to operwall/globops - This depends on the IRCd and will need specific support in the protocol modules.

**Comment by jameswritescode** [comment]
How about just adding logging as a configurable thing, and the level also be part of that configuration?

**Comment by GLolol** [comment]
Yeah, that would be awesome. It'd have 3 options: file, channel, and STDOUT. Right now, the only configurable log-related thing is the log level, and anything other than DEBUG isn't really complete yet.
